name: iosApp
options:
  bundleIdPrefix: org.opencampus
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    CODE_SIGNING_ALLOWED: "NO"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"
targets:
  iosApp:
    type: application
    platform: iOS
    sources: [iosApp]
    info:
      path: iosApp/Info.plist
      properties:
        CFBundleDisplayName: OSS eLearning
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.opencampus.elearning
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LDFLAGS: ["$(inherited)", "-framework", "ComposeApp"]
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
